[package]
name = "sqlite-regex"
version = "0.0.0-alpha.1"
edition = "2021"

[dependencies]
#sqlite-loadable = {path="../sqlite-loadable-rs"}
sqlite-loadable = "0.0.5"
regex = "1"

[lib]
crate-type=["lib", "cdylib", "staticlib"]